# Generated by Django 2.0.7 on 2018-11-04 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedCandidate',
            fields=[
                ('AccCandidateID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('CandidateID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Major', models.CharField(max_length=50)),
                ('LastDegree', models.CharField(choices=[('Ph.D.', 'Ph.D.'), ('Master', 'Master'), ('BS', 'BS')], default='BS', max_length=20)),
                ('GPA', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('DateofBirth', models.DateField()),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('YearsExperirence', models.IntegerField(default=0)),
                ('Skills', models.CharField(default='none', max_length=200)),
                ('IsHired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSSN',
            fields=[
                ('SSNID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SSN', models.IntegerField()),
                ('CandidateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RM.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentNo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('DepartmentName', models.CharField(choices=[('Marketing', 'Marketing'), ('HR Management', 'HR Management'), ('Production/Engineering', 'Production/Engineering')], default='Marketing', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeNumber', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('HiringDate', models.DateField(auto_now=True)),
                ('DateofBirth', models.DateField()),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('AccCandidateID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RM.AcceptedCandidate')),
                ('DepartmentNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RM.Department')),
                ('ManagerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RM.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('SalaryId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('Year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('EmployeeNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RM.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryUnit',
            fields=[
                ('SalaryUId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('IsItIncome', models.BooleanField(default=True)),
                ('SalaryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RM.Salary')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='SalaryUId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RM.SalaryUnit'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='SalaryUId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RM.SalaryUnit'),
        ),
        migrations.AddField(
            model_name='acceptedcandidate',
            name='CandidateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RM.Candidate'),
        ),
        migrations.AddField(
            model_name='acceptedcandidate',
            name='SSNID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RM.CandidateSSN'),
        ),
    ]
